# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0004_auto_20170430_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='initial',
            field=models.BooleanField(default=False),
        ),
    ]
