# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0005_signature_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
