# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 13:34
from __future__ import unicode_literals

from django.db import models, migrations


def load_first_petition(apps, schema_editor):
    Petition = apps.get_model('petitions', 'Petition')
    first_petition = Petition(title='Our 1st petition', body='A first petition')
    first_petition.save()


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0006_auto_20170430_1939'),
    ]

    operations = [
        migrations.RunPython(load_first_petition),
    ]
