# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0007_auto_20170513_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='affiliation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
